### ISSUE TITLE
Could you provide the pretrained resnet50_k3_pasa_group8_softmax model?

### ISSUE THREAD

**Issue by somebody-deep** [MaureenZOU/Adaptive-anti-Aliasing#1]
This is an interesting work. Could you provide the pretrained resnet50_k3_pasa_group8_softmax model? Thank you.

**Comment by MaureenZOU** [comment]
Thanks for your interesting : ) I currently do not have resnet50_k3_pasa_group9_softmax model. If more than 3 persons are asking for that I will consider training one. Thanks!

**Comment by zhengchaobing** [comment]
+1

**Comment by MaureenZOU** [comment]
I will temporally close this issue, and will bare training resnet50 in mind after I get through these busy months before CVPR.

**Comment by mittlin** [comment]
+1

**Comment by bluoluo** [comment]
+1

**Comment by somebody-deep** [comment]
Hi CVPR's deadline has gone, could you provide the resnet50 and resnet18 models?

**Comment by MaureenZOU** [comment]
Hi, sorry for replying this a bit late. I have just release a beta version of segmentation code and working on ResNet 50 : )

**Comment by anirudh-chakravarthy** [comment]
Hi,

I can't seem to find the pre-trained weights with ResNet-50 backbone. Can you provide that? 

Additionally, do you plan to release COCO weights? That would be great!

**Comment by Soarkey** [comment]
Hi, Could you have plans that continue to release resnet50 models?  +_+
