### ISSUE TITLE
anti-aliasing filter size is 5 in testing but 3 in training? filter size matters?

### ISSUE THREAD

**Issue by mrj-taffy** [MaureenZOU/Adaptive-anti-Aliasing#3]

**Comment by MaureenZOU** [comment]
I apologize for the confusion, the training filter size and testing filter size is the same. It is a typo.

**Comment by mrj-taffy** [comment]
thanks!
 It's a great job and I am using pasa in segmentaion project. 
 And I wonder how that In your readme file, "Please directly put "Adaptive-anti-Aliasing/models_lpf/layers/pasa.py" this module before downsampling layers of the backbone except the first convolution layer." means downsampling applied in conv or pool not in the pasa module?(stride=1 or 2 in pasa ? )

**Comment by MaureenZOU** [comment]
Oh, Thanks for your question. I think I also need to clarify this. Downsampling always applied in pasa module. I change all the stride=2 to 1 in conv layers and move it to pasa.
