### ISSUE TITLE
Missing dilate to work with DeepLabV3+

### ISSUE THREAD

**Issue by edizhuang** [MaureenZOU/Adaptive-anti-Aliasing#5]
Is this the working code with DeepLabV3+ implementation from VainF? It seems this ResNet implementation is missing dilate for _make_layer() function and Bottleneck unit, and missing replace_stride_with_dilation argument to work with DeepLabV3+.

**Comment by MaureenZOU** [comment]
Yes, this version is only for image classification. And if you are working with deeplab, please insert the PASA module before all the downsample layer except for the first one.

**Comment by MaureenZOU** [comment]
And I plan to release semseg code.

**Comment by MaureenZOU** [comment]
Semantic Segmentation beta version code for Pascal VOC is released .
