### ISSUE TITLE
why using softmax in groups*k_size*k_size?

### ISSUE THREAD

**Issue by Rookielike** [MaureenZOU/Adaptive-anti-Aliasing#6]
Thanks for your code.I wonder why using softmax in groups * k_size * k_size instead of k_size * k_size? My understanding is that the kernel shape is k_size * k_size and  there are "groups" kernels. So the sum of each kernel should be 1 instead of  "groups" kernels

**Comment by MaureenZOU** [comment]
Thanks for your question : ) Please refer this question to "Learning to predict filters" section in the paper. When groups=1, it is exactly "k^2", and practically applying softmax on "groups" gives more freedom for the kernel weights, at the same time, the network will also predict "lowpass" filter at where it needs. Further I have tried out softmax on each group separately, it gives very similar result.
