### ISSUE TITLE
Instance Segmentation

### ISSUE THREAD

**Issue by anirudh-chakravarthy** [MaureenZOU/Adaptive-anti-Aliasing#7]
Hi,

When do you plan to release the Instance segmentation branch? I would be extremely grateful if it were made available.

Additionally, if you could also provide ResNet-50/101 COCO pre-trained weights, that would be great!

**Comment by MaureenZOU** [comment]
I sincerely apologize for delaying reply the issues. Have just released instance segmentation branch.
