### ISSUE TITLE
Doubt about the pasa with involution

### ISSUE THREAD

**Issue by yyknight** [MaureenZOU/Adaptive-anti-Aliasing#8]
Thanks for your impressive work. However, I noticed the operation in paper "Involution: Inverting the Inherence of Convolution for Visual Recognition (CVPR'21)" is highly similar with yours. Is there any difference? this paper just introduced the pasa into normal convolution rather than downsampling?

**Comment by MaureenZOU** [comment]
Thanks for your interests in our work : )
